### PR TITLE
Code Review

### PR DESCRIPTION
**Pull request by AntonioHincapie**
- Set up the repository.
- Create the rails app.
- Set up the initial configuration of the app.
- Create a data model.
- Create models, relations, and validations
- Install RSpec.
- Config bullet.
- Install and configure the devise gem.
- Install and configure the  CanCanCan gem.
- Create a home.
- Add data to show (seed database).
- Create a landing page.
- Create and config controllers.
- Create and config views.
- Add fonts and logo.
- Add style based in [Template](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=).
- Create integration specs.
- Create model specs.
- Deploy the app with Heroku.
- Create a README file.

- Descriptive [Loom video](https://www.loom.com/share/68f4d69170984f5c897d98fe35da5030)

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Antonio, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has incorrect gitflow/ GitHub flow. Kindly note that capstone projects worked on by a single contributor should have merge request **from feature into development**. Kindly use the correct gitflow and request another code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by AntonioHincapie** [comment]
> Hi Antonio,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that has incorrect gitflow/ GitHub flow. Kindly note that capstone projects worked on by a single contributor should have merge request **from feature into development**. Kindly use the correct gitflow and request another code review.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Hello, @rloterh 

Can you please send me, WHERE in the git flow instructions says this?

**Review by RolandM99 — APPROVED** [review]
<h1>Status: Approve 🥇 ✔</h1>
Hi @AntonioHincapie , 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## KUDOS! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rloterh** [comment]
Hi @AntonioHincapie 
I'm not sure if you're not informed of this as a student, else this needs to be updated in your instructional docs. This has however been discussed among the code reviewers.

Cheers!

**Pull request merged**
